title: Tecnual
description: Tecnología intelectual
url: "http://blog.tecnual.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog

# Comments
discus_identifier: tecnual

# Social settings
twitter_url: https://twitter.com/tecnual
facebook_url: https://facebook.com/tecnual
github_url: https://github.com/tecnual/

# Analytics

google_analytics: UA-1207384-8
